[target.x86_64-pc-windows-gnu]
# image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:main"
# pre-build = ["apt-get update && apt-get install --assume-yes --no-install-recommends libclang-dev clang"]
linker = "/usr/bin/clang"
